name: WireGuard Config Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard & QR tool
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard qrencode
          
          umask 077
          wg genkey | tee privatekey | wg pubkey > publickey
          
          PRIVATE_KEY=$(cat privatekey)
          PUBLIC_KEY=$(cat publickey)
          
          echo "[Interface]
PrivateKey = $PRIVATE_KEY
Address = 10.0.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = $PUBLIC_KEY
Endpoint = dummy.com:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25" > wg0.conf

          echo "✅ فایل کانفیگ ساخته شد:"
          cat wg0.conf
          echo "📷 QR Code:"
          qrencode -t UTF8 < wg0.conf
